// dom.js — element cache + UI constants. The DOM object is a dependency
// leaf (imports nothing): every other module may import it read-only.
// NOTE: main.js must stay at end of <body> (or be deferred, as with
// type="module") so these lookups resolve at evaluation time.
export const DOM = {
    btn: document.getElementById('searchBtn'), loadMoreBtn: document.getElementById('loadMoreBtn'), resetBtn: document.getElementById('resetBtn'),
    grid: document.getElementById('bookGrid'), status: document.getElementById('statusMessage'),
    footer: document.getElementById('resultsFooter'), hiddenMsg: document.getElementById('hiddenMessage'),
    resultsHeader: document.getElementById('resultsHeader'), resultsMeta: document.getElementById('resultsMeta'),
    totalCount: document.getElementById('totalCount'), stageToasts: document.getElementById('stageToasts'),
    fetchStatus: document.getElementById('fetchStatus'),
    copyUrlBtn: document.getElementById('copyUrlBtn'), persistToggle: document.getElementById('persistToggle'),
    incSub: document.getElementById('incSubject'), incLang: document.getElementById('incLang'),
    incTitle: document.getElementById('incTitle'), incAuthor: document.getElementById('incAuthor'),
    incPlace: document.getElementById('incPlace'), incPerson: document.getElementById('incPerson'),
    excSub: document.getElementById('excSubject'), excLang: document.getElementById('excLang'),
    excPlace: document.getElementById('excPlace'), excPerson: document.getElementById('excPerson'),
    minY: document.getElementById('minYear'), maxY: document.getElementById('maxYear'),
    minStarRating: document.getElementById('minStarRating'), minRatings: document.getElementById('minRatings'),
    sort: document.getElementById('sortSelect'), sortNote: document.getElementById('sortNote'),
    sortDateOpt: document.getElementById('sortDateOpt'), sortRelevanceOpt: document.getElementById('sortRelevanceOpt'),
    viewSavedBtn: document.getElementById('viewSavedBtn'), savedCount: document.getElementById('savedCount'),
    customLimitToggle: document.getElementById('customLimitToggle'),
    customLimitContainer: document.getElementById('customLimitContainer'),
    fetchLimitSlider: document.getElementById('fetchLimitSlider'),
    limitValueDisplay: document.getElementById('limitValueDisplay'),
    extendedLimitWrapper: document.getElementById('extendedLimitWrapper'),
    extendedLimitToggle: document.getElementById('extendedLimitToggle'),
    extendedWarning: document.getElementById('extendedWarning'),
    enhancedAutofillToggle: document.getElementById('enhancedAutofillToggle'),
    apiAdvancedSettings: document.getElementById('apiAdvancedSettings'),
    searchOptionsCategory: document.getElementById('searchOptionsCategory'),
    querySpeedContainer: document.getElementById('querySpeedContainer'),
    querySpeedTooltip: document.getElementById('querySpeedTooltip'),
    listViewToggle: document.getElementById('listViewToggle'),
    toggleAllBtn: document.getElementById('toggleAllBtn'),
    globalSearchInput: document.getElementById('globalSearchInput'),
    globalSearchClearBtn: document.getElementById('globalSearchClearBtn'),
    homeBtn: document.getElementById('homeBtn'),
    globalSearchBtn: document.getElementById('globalSearchBtn'),
    discoverDashboard: document.getElementById('discoverDashboard'),
    discoverDashboardToggles: document.getElementById('discoverDashboardToggles'),
    toggleTrendingBtn: document.getElementById('toggleTrendingBtn'),
    toggleGenresBtn: document.getElementById('toggleGenresBtn'),
    settingsBtn: document.getElementById('settingsBtn'),
    settingsPanel: document.getElementById('settingsPanel'),
    settingsCloseBtn: document.getElementById('settingsCloseBtn'),
    translateToggle: document.getElementById('translateToggle'),
    translateCoversToggle: document.getElementById('translateCoversToggle'),
    translateCoversRow: document.getElementById('translateCoversRow'),
    completeTranslateToggle: document.getElementById('completeTranslateToggle'),
    completeTranslationRow: document.getElementById('completeTranslationRow'),
    reduceAnimationsToggle: document.getElementById('reduceAnimationsToggle'),
    compactHeaderToggle: document.getElementById('compactHeaderToggle'),
    legacyLayoutToggle: document.getElementById('legacyLayoutToggle'),
    sidebarSideToggle: document.getElementById('sidebarSideToggle'),
    cleanSynopsisToggle: document.getElementById('cleanSynopsisToggle'),
    resetSettingsBtn: document.getElementById('resetSettingsBtn'),
    sidebarStickyHeader: document.getElementById('sidebarStickyHeader'),
    legacySlotAnchor: document.getElementById('legacySlotAnchor'),
    detailsDrawer: document.getElementById('detailsDrawer'),
    detailsBackdrop: document.getElementById('detailsBackdrop'),
    detailsCloseBtn: document.getElementById('detailsCloseBtn'),
    detailsCoverContainer: document.getElementById('detailsCoverContainer'),
    detailsTitle: document.getElementById('detailsTitle'),
    detailsAuthor: document.getElementById('detailsAuthor'),
    detailsYear: document.getElementById('detailsYear'),
    detailsRating: document.getElementById('detailsRating'),
    detailsDescription: document.getElementById('detailsDescription'),
    detailsSubjects: document.getElementById('detailsSubjects'),
    detailsLibraryBtn: document.getElementById('detailsLibraryBtn'),
    detailsDownloadLink: document.getElementById('detailsDownloadLink'),
    detailsOlBtn: document.getElementById('detailsOlBtn'),
    selectionBar: document.getElementById('selectionBar'),
    selectionCloseBtn: document.getElementById('selectionCloseBtn'),
    selectionCount: document.getElementById('selectionCount'),
    selectionSelectAllBtn: document.getElementById('selectionSelectAllBtn'),
    selectionBulkBtn: document.getElementById('selectionBulkBtn'),
    exportLibraryBtn: document.getElementById('exportLibraryBtn'),
    importLibraryBtn: document.getElementById('importLibraryBtn'),
    importFileInput: document.getElementById('importFileInput'),
    importStatusMsg: document.getElementById('importStatusMsg'),
    cleanLibrarySubjectsToggle: document.getElementById('cleanLibrarySubjectsToggle'),
    smoothScrollingToggle: document.getElementById('smoothScrollingToggle'),
    pinSettingsToggle: document.getElementById('pinSettingsToggle'),
    telemetryFloatingModal: document.getElementById('telemetryFloatingModal'),
    telemetryPinBtn: document.getElementById('telemetryPinBtn'),
    telemetryCloseBtn: document.getElementById('telemetryCloseBtn'),
    telemetryHeaderDraggable: document.getElementById('telemetryHeaderDraggable'),
    clearLibraryCacheBtn: document.getElementById('clearLibraryCacheBtn'),
    libraryTranslateProgress: document.getElementById('libraryTranslateProgress'),
    libraryTranslateProgressBar: document.getElementById('libraryTranslateProgressBar'),
    viewShortcutsBtn: document.getElementById('viewShortcutsBtn'),
    shortcutsModal: document.getElementById('shortcutsModal'),
    shortcutsModalCloseBtn: document.getElementById('shortcutsModalCloseBtn'),
    shortcutsModalBackdrop: document.getElementById('shortcutsModalBackdrop')
};
export const watchInputs = document.querySelectorAll('.watch-input');
export const INPUT_IDS = ['globalSearchInput', 'incLang', 'incTitle', 'incAuthor', 'incPlace', 'incPerson', 'excLang', 'excPlace', 'excPerson', 'minYear', 'maxYear', 'minStarRating', 'minRatings'];
export const RENDER_CHUNK = 50;
